Repository scikit-hep/mplhep, pull requests merged in 2020-03, with the labels that each got.

#90 feat: Unicode minus in CMS style as well
  mplhep/styles_cms.py
Labels: bumpversion/patch

#91 Improve CI
  .github/workflows/tag.yml
Labels: CI

#92 docs: Revise section on use in publications
  README.md
Labels: bumpversion/patch

#93 feat: Sync styles, add style tests
  .github/workflows/ci.yml
  README.md
  mplhep/cms.py
  mplhep/plot.py
  mplhep/styles.py
  mplhep/styles_cms.py
  mplhep/styles_lhcb.py
  mplhep/tools.py
  tests/baseline/test_basic.png
  tests/baseline/test_hist2dplot.png
  tests/baseline/test_histplot.png
  tests/baseline/test_histplot_density.png
  tests/baseline/test_histplot_kwargs.png
  tests/baseline/test_histplot_multiple.png
  tests/baseline/test_histplot_stack.png
  tests/baseline/test_style_atlas.png
  tests/baseline/test_style_cms.png
  tests/baseline/test_style_lhcb.png
  tests/baseline/test_times_new_roman.png
  tests/test.py
Labels: bumpversion/patch

#88 fix: update font registration
  mplhep/__init__.py
  setup.py
Labels: mpl3.2+

#99 Allow hist objects to go into histplot(), Use edges by default, small fixes
  mplhep/plot.py
  tests/baseline/test_basic.png
  tests/baseline/test_hist2dplot.png
  tests/baseline/test_histplot.png
  tests/baseline/test_histplot_density.png
  tests/baseline/test_histplot_kwargs.png
  tests/baseline/test_histplot_multiple.png
  tests/baseline/test_histplot_stack.png
  tests/baseline/test_style_atlas.png
  tests/baseline/test_style_cms.png
  tests/baseline/test_style_lhcb.png
  tests/test.py
Labels: backport master-py27, bumpversion/patch

#105 Backport/99 to master py27
  mplhep/plot.py
  tests/baseline/test_basic.png
  tests/baseline/test_histplot.png
  tests/baseline/test_histplot_density.png
  tests/baseline/test_histplot_kwargs.png
  tests/baseline/test_histplot_multiple.png
  tests/baseline/test_histplot_stack.png
  tests/baseline/test_style_atlas.png
  tests/baseline/test_style_cms.png
  tests/baseline/test_style_lhcb.png
  tests/test.py
Labels: bumpversion/patch

#106 Errorbar: Use right labels
  mplhep/plot.py
Labels: backport master-py27, bumpversion/patch
